# PLAY level variables
- name: variables from PLAY level
  hosts: localhost
  vars:
    Course: "DevOps"  #To acess variable use curl brackets{{}}
    Trainer: "Sivakumar"
    Duration: "110HRS"
  tasks:
  - name: check variables
    ansible.builtin.debug:
      msg: "Hi, I am learning {{Course}}, Trainer is {{Trainer}}, Duration is {{Duration}}" 