- name: ping playbook    #Name of the palybook
  hosts: client          #Host name which is mentioned in inventory file 
  tasks: 
  - name: ping the node server #Name of the task
    ansible.builtin.ping:


#We are giving our username nad password in terminal or ansible.cfg file which is not secure so use vault.